# Demo Tensor
* `linear_model` is `Tensor`

In [13]:
import os
import time
import tensorflow.compat.v1 as tf
tf.disable_v2_behavior() 

W = tf.Variable([.3], dtype=tf.float32, name="myW")
b = tf.Variable([-.3], dtype=tf.float32, name="myb")
x = tf.placeholder(tf.float32, name="myx")
linear_model = W*x + b

print(linear_model)

Tensor("add_4:0", dtype=float32)


In [14]:
init = tf.global_variables_initializer()
sess = tf.Session()
sess.run(init)
for i in range(3):
    print("result of linear model")
    print(sess.run(linear_model, {x: [1, 2, 3, 4]}))
    print("each variable")
    curr_W, curr_b = sess.run([W, b], {x: [1, 2, 3, 4]})
    print(f"W: {curr_W}, b:{curr_b}")

result of linear model
[0.         0.3        0.6        0.90000004]
each variable
W: [0.3], b:[-0.3]
result of linear model
[0.         0.3        0.6        0.90000004]
each variable
W: [0.3], b:[-0.3]
result of linear model
[0.         0.3        0.6        0.90000004]
each variable
W: [0.3], b:[-0.3]


* Saving Tensors itself is useless, because they are just a group of numbers
  * Tensors can be saved with numpy library
* The sess can be saved and loaded

In [17]:
saver = tf.train.Saver()
now = time.time()
os.mkdir(f'../artifacts/{now}/')
saver.save(sess, f'../artifacts/{now}/')

print(now)
os.listdir(f'../artifacts/{now}/')

1625390817.8325164


['.meta', 'checkpoint', '.index', '.data-00000-of-00001']

* `.meta` is the graph file