In [24]:
import tensorflow as tf

W = tf.Variable([[.1, .2, .3], [.2, .4, .6]], dtype=tf.float32)
b = tf.Variable([[.2], [.3]], dtype=tf.float32)
x = tf.placeholder(tf.float32)

linear_model = W*x + b

init = tf.global_variables_initializer()
sess = tf.Session()
sess.run(init)
print(sess.run(linear_model, {x: [1., 2., 3.]}))


[[0.3       0.6       1.1      ]
 [0.5       1.1       2.1000001]]


In [25]:
summary = tf.reduce_sum(linear_model)
print(sess.run(summary, {x: [1., 2., 3.]}))

summary_1 = tf.reduce_sum(linear_model, 1)
print(sess.run(summary_1, {x: [1., 2., 3.]}))

5.7
[2.        3.7000003]


In [26]:
sig = tf.nn.sigmoid(summary_1)
print(sess.run(sig, {x: [1., 2., 3.]}))

[0.880797 0.975873]


In [27]:
y = tf.placeholder(tf.float32)

err = tf.square(sig - y)
loss = tf.reduce_sum(err)

x_train = [1., 2., 3.]
y_train = [0., 1.]

init = tf.global_variables_initializer()
sess = tf.Session()
sess.run(init)
for i in range(3):
  print(sess.run(loss, {x: x_train, y: y_train}))

  curr_W, curr_b, curr_loss = sess.run([W, b, loss], {x: x_train, y: y_train})
  print("W: %s b: %s loss: %s"%(curr_W, curr_b, curr_loss))

0.7763855
W: [[0.1 0.2 0.3]
 [0.2 0.4 0.6]] b: [[0.2]
 [0.3]] loss: 0.7763855
0.7763855
W: [[0.1 0.2 0.3]
 [0.2 0.4 0.6]] b: [[0.2]
 [0.3]] loss: 0.7763855
0.7763855
W: [[0.1 0.2 0.3]
 [0.2 0.4 0.6]] b: [[0.2]
 [0.3]] loss: 0.7763855


In [33]:
# build-in optimizer
optimizer = tf.train.GradientDescentOptimizer(0.01)
train = optimizer.minimize(loss)

for i in range(5):
  print(sess.run(train, {x: x_train, y: y_train}))

  curr_W, curr_b, curr_loss = sess.run([W, b, loss], {x: x_train, y: y_train})
  print("W: %s\nb: %s\nloss: %s"%(curr_W, curr_b, curr_loss))

  curr_Sig, curr_y, curr_err = sess.run([sig, y, err], {x: x_train, y: y_train})
  print("Sig: %s\ny: %s\nerr: %s"%(curr_Sig, curr_y, curr_err))

None
W: [[0.03169956 0.06339911 0.09509867]
 [0.20030476 0.40060952 0.60091436]]
b: [[-0.00490132]
 [ 0.30091435]]
loss: 0.3673938
Sig: [0.6056563 0.9760375]
y: [0. 1.]
err: [0.3668196 0.0005742]
None
W: [[0.0288065  0.05761299 0.08641949]
 [0.20031597 0.40063193 0.600948  ]]
b: [[-0.01358049]
 [ 0.30094796]]
loss: 0.3482698
Sig: [0.5896574 0.9760435]
y: [0. 1.]
err: [0.3476959  0.00057391]
None
W: [[0.02595301 0.05190602 0.07785902]
 [0.20032717 0.40065435 0.6009816 ]]
b: [[-0.02214096]
 [ 0.30098158]]
loss: 0.32969296
Sig: [0.5736892  0.97604954]
y: [0. 1.]
err: [0.32911932 0.00057362]
None
W: [[0.02314687 0.04629373 0.0694406 ]
 [0.20033836 0.40067673 0.6010152 ]]
b: [[-0.03055939]
 [ 0.30101517]]
loss: 0.31175268
Sig: [0.5578345  0.97605556]
y: [0. 1.]
err: [0.31117934 0.00057334]
None
W: [[0.02039501 0.04079002 0.06118503]
 [0.20034955 0.4006991  0.60104877]]
b: [[-0.03881495]
 [ 0.30104876]]
loss: 0.29452232
Sig: [0.5421709 0.9760616]
y: [0. 1.]
err: [0.29394928 0.00057305]
