# The value of placeholder is provided at runtime 

In [1]:
import tensorflow as tf

a = tf.placeholder(tf.float32)
b = tf.placeholder(tf.float32)

adder_node2 = tf.add(a, b)
# + provides a shortcut for tf.add(a, b)
adder_node = a + b 

sess = tf.Session()
print(sess.run(adder_node, {a: 3, b: 4.5}))
print(sess.run(adder_node2, {a: 3, b: 4.5}))

7.5
7.5


# The input can be in different format

In [2]:
print(sess.run(adder_node, {a: [1, 3], b: [2, 4]}))
print(sess.run(adder_node2, {a: [1, 3], b: [2, 4]}))

[3. 7.]
[3. 7.]


## multiply by 3

In [4]:
add_and_triple = adder_node * 3.
print(sess.run(add_and_triple, {a: 3, b: 4.5}))

add_and_triple2 = adder_node2 * 3.
print(sess.run(add_and_triple2, {a: 3, b: 4.5}))

22.5
22.5


# multiply operation

In [30]:
W = tf.placeholder(tf.float32)
x = tf.placeholder(tf.float32)

print(sess.run(W*x, {W: [[1, 2, 3], [4, 5, 6]], x: [1, 2, 3]}))

[[ 1.  4.  9.]
 [ 4. 10. 18.]]


## they will generate the same results

In [32]:
print(sess.run(W*x, {W: [[1], [2], [3]], x: [1, 2, 3]}))
print(sess.run(W*x, {W: [[1, 2, 3]], x: [[1], [2], [3]]}))

[[1. 2. 3.]
 [2. 4. 6.]
 [3. 6. 9.]]
[[1. 2. 3.]
 [2. 4. 6.]
 [3. 6. 9.]]


## they will generate different results

In [34]:
print(sess.run(tf.matmul(W, x), {W: [[1], [2], [3]], x: [[1, 2, 3]]}))
print(sess.run(tf.matmul(W, x), {W: [[1, 2, 3]], x: [[1], [2], [3]]}))

[[1. 2. 3.]
 [2. 4. 6.]
 [3. 6. 9.]]
[[14.]]


In [36]:
print(sess.run(tf.matmul(W, x), {
    W: [[1, 2, 3], [1, 2, 3]], 
    x: [[1], [2], [3]]}))

[[14.]
 [14.]]
